# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

process_snptext_cpp <- function(df, snpmajor = 0L, maref = 0L, inhaplo = 0L, outallele = 1L, outhaplo = 0L) {
    .Call('_r3_process_snptext_cpp', PACKAGE = 'r3', df, snpmajor, maref, inhaplo, outallele, outhaplo)
}

read_bed_cpp <- function(file, nind, nsnp) {
    .Call('_r3_read_bed_cpp', PACKAGE = 'r3', file, nind, nsnp)
}

twostep_grm_cpp <- function(genotype, freq, est0) {
    .Call('_r3_twostep_grm_cpp', PACKAGE = 'r3', genotype, freq, est0)
}

write_markers_cpp <- function(marker, freq, genotype, memberID, outfile) {
    invisible(.Call('_r3_write_markers_cpp', PACKAGE = 'r3', marker, freq, genotype, memberID, outfile))
}

